### ISSUE TITLE
Sublime Text 4 ?

### ISSUE THREAD

**Issue by cristiandley** [jrappen/sublime-auto-dark#1]
Is this really for ST4 ?

**Comment by jrappen** [comment]
Yes

**Comment by jrappen** [comment]
@christiandley I could add a branch for ST3 when I‘m back from my trip abroad, if that helps.

**Comment by jrappen** [comment]
@cristiandley ST3 support (for osx and windows) was added in jrappen/sublime-auto-dark@9009d30

**Comment by cristiandley** [comment]
@jrappen Amazing !!!

**Comment by josegonzalez** [comment]
Is there a way to install the ST3 version from PackageControl? It's not showing up there for me (but not sure if it should).

**Comment by jrappen** [comment]
ST3 support has been removed due to limited time and resources on my end.

---

There is a closed ST4 beta:

https://discord.gg/D43Pecu

Assuming you have a valid ST3 license, you can find the download links there.
