### ISSUE TITLE
Don't understand how to make it work

### ISSUE THREAD

**Issue by nikitavoloboev** [jrappen/sublime-auto-dark#4]
I read through

https://github.com/jrappen/sublime-auto-dark/blob/master/docs/README.en.md#usage

And saw @jrappen linked to https://github.com/jrappen/sublime-auto-dark/blob/master/src/auto_dark.py#L64-L67

But I don't get how can I make it work with https://github.com/dempfi/ayu I am running. I want it to switch to Ayu Mirage both Theme and UI on dark and Ayu Light both the theme & UI on dark. 

I assume I have to add code like `cs_now = pref.get('color_scheme', 'Monokai.sublime-color-scheme')` somewhere? It's not really clear.

Thanks

**Comment by dangh** [comment]
@nikitavoloboev You can add these keys to your preference. For example:

```
"theme.dark": "1Space-Dark.sublime-theme",
"theme.light": "1Space-Light.sublime-theme",
"color_scheme.dark": "OneDarkPro.sublime-color-scheme",
"color_scheme.light": "GitHub.sublime-color-scheme",
```

**Comment by jespertheend** [comment]
Ah I was looking for the auto-dark preference file somewhere, but I wasn not aware you had to place these entries in your current `Preferences.sublime-settings`. You might want to consider adding that to the documentation.
It makes a lot of sense to put it there though, I like it!
Thanks for this plug-in :)
